title: LogicPad
# シンプルなローコードツール「LogicPad」の公式ページです。

description: "LogicPad Official Website. A simple low-code tool for building any type of application."
github_username:  kenjinote

theme: minima
plugins:
  - jekyll-feed

exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
  - README.md
  