title: ToshioCP's Homepage
description: "ToshioCP's Homepage mainly contains computer software."
github_username:  ToshioCP

theme: minima
plugins:
  - jekyll-feed

exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
  - README.md
  